config/routes.rb
Whoot::Application.routes.draw do

  match '(*any)' => redirect { |p, req| req.url.sub('www.', '') }, :constraints => { :host => /^www\./ }

  scope 'api' do
    scope 'v2' do
      scope 'posts' do
        get 'feed' => 'api_posts#feed', :defaults => { :format => :api }
        get ':id' => 'api_posts#show', :defaults => { :format => :api }
        post '' => 'api_posts#create', :defaults => { :format => :api }

        scope 'loop_ins' do
          post '' => 'api_loop_ins#create', :type => 'User', :defaults => { :format => :api }
          delete '' => 'api_loop_ins#destroy', :type => 'User', :defaults => { :format => :api }
        end
      end

      scope 'users' do
        scope 'follows' do
          post '' => 'api_follows#create', :type => 'User', :defaults => { :format => :api }
          delete '' => 'api_follows#destroy', :type => 'User', :defaults => { :format => :api }
        end

        scope 'blocked' do
          post '' => 'api_users#block_user', :defaults => { :format => :api }
          get '' => 'api_users#blocked_users', :defaults => { :format => :api }
          delete '' => 'api_users#unblock_user', :defaults => { :format => :api }
        end

        scope 'pings' do
          post '' => 'api_pings#create', :type => 'User', :defaults => { :format => :api }
        end

        put '' => 'api_users#update', :defaults => { :format => :api }
        put 'location' => 'api_users#change_location', :defaults => { :format => :api }, :as => :user_change_location
        post 'night_invites' => 'api_users#night_invite', :defaults => { :format => :api }
        get 'me' => 'api_users#me', :defaults => { :format => :api }
        get 'undecided' => 'api_users#undecided', :defaults => { :format => :api }
        get 'notifications' => 'api_users#notifications', :defaults => { :format => :api }
        get ':id/activity' => 'api_users#activity', :defaults => { :format => :api }
        get ':id/following_users' => 'api_users#following_users', :defaults => { :format => :api }
        get ':id/followers' => 'api_users#followers', :defaults => { :format => :api }
        get ':id' => 'api_users#show', :defaults => { :format => :api }
      end

      scope 'comments' do
        post '' => 'api_comments#create', :as => :comments_create, :defaults => { :format => :api }
      end

      scope 'invites' do
        post 'phone_numbers' => 'invites#invite_phone_numbers', :defaults => { :format => :api }
        get 'show_invite_screen' => 'invites#show_invite_screen', :defaults => { :format => :api }
      end

      scope 'shouts' do
        post '' => 'shouts#create', :defaults => { :format => :api }
      end

      get 'locations' => 'api_locations#index', :defaults => { :format => :api }
      get 'facebook-friends' => 'api#facebook_friends', :defaults => { :format => :api, :version => :v2 }
      get 'analytics' => 'api_users#analytics', :as => :analytics, :defaults => { :format => :api }
      get 'generate_token' => 'api#generate_token', :as => :mobile_generate_token, :defaults => { :format => :api }
      post 'set_device_token' => 'api#set_device_token', :as => :set_device_token, :defaults => { :format => :api }
    end

    scope 'v1' do
      get 'generate_token' => 'api#generate_token', :as => :mobile_generate_token, :defaults => { :format => :api }
      post 'set_device_token' => 'api#set_device_token', :as => :set_device_token, :defaults => { :format => :api }
      get 'posts' => 'api#posts', :defaults => { :format => :api }
      post 'posts' => 'posts#create', :defaults => { :format => :api }
      get 'posts/:id/comments' => 'api#comments', :defaults => { :format => :api }
      post 'posts/comments' => 'comments#create', :defaults => { :format => :api }
      get 'posts/:id/votes' => 'api#votes', :defaults => { :format => :api }
      post 'posts/votes' => 'votes#create', :defaults => { :format => :api }
      post 'follow' => 'follows#create', :defaults => { :format => :api }
      delete 'follow' => 'follows#destroy', :defaults => { :format => :api }
      post 'ping' => 'pings#create', :defaults => { :format => :api }
      get 'undecided' => 'api#undecided', :defaults => { :format => :api }
      get 'facebook-friends' => 'api#facebook_friends', :defaults => { :format => :api, :version => :v1 }
      get 'users/me' => 'api#me', :defaults => { :format => :api }
      get 'users/:id/following' => 'users#following_users', :defaults => { :format => :api }
      get 'users/:id/followers' => 'users#followers', :defaults => { :format => :api }
      get 'users/:id' => 'users#show', :defaults => { :format => :api }
      post 'invites/phone_numbers' => 'invites#invite_phone_numbers', :defaults => { :format => :api }
      get 'invites/show_invite_screen' => 'invites#show_invite_screen', :defaults => { :format => :api }
    end
  end

  scope 'm' do
    scope 'p' do
      get ':id' => 'mobile#post_show'
    end
  end

  get 'settings' => 'users#settings', :as => :user_settings
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  get '/users/auth/:provider' => 'omniauth_callbacks#passthru'

  scope "/users" do
    put "/picture" => "users#picture_update", :as => :user_picture_update
    get ':id/picture' => 'users#default_picture', :as => :user_default_picture
    put '/location' => 'users#change_location'
  end

  get ':id/following' => 'users#show', :as => :user_following_users
  get ':id/followers' => 'users#show', :as => :user_followers

  resque_constraint = lambda do |request|
    request.env['warden'].authenticate? and request.env['warden'].user.role?('admin')
  end

  constraints resque_constraint do
    mount Resque::Server, :at => "admin/resque"
  end

  mount Soulmate::Server, :at => "soul-data"

  resources :invites, :only => [:create, :index]

  resources :posts, :only => [:new]

  get 'testing' => 'testing#test', :as => :test

  get ':id' => 'users#show', :as => :user

  scope 'pages' do
    get 'about' => 'pages#about', :as => :about
    get 'contact' => 'pages#contact', :as => :contact
    get 'terms' => 'pages#terms', :as => :terms
    get 'privacy' => 'pages#privacy', :as => :privacy
    get 'faq' => 'pages#faq', :as => :faq
    get 'team' => 'pages#team', :as => :team
  end

  root :to => "pages#home"

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => :default_picture
  include ImageHelper

  caches_action :default_picture, :cache_path => Proc.new { |c| "#{c.params[:id].split('-')[0]}-#{c.params[:d][0]}-#{c.params[:d][1]}-#{c.params[:s]}" }

  def show
    @this = params[:id] && params[:id] != "0" ? User.find(params[:id]) : current_user

    not_found("User not found") unless @this
    @title = @this.username
    @description = "Everything #{@this.fullname} on The Whoot."

    if current_user.blocked_by.include?(@this.id)
      redirect_to root_path
    end
  end

  def default_picture
    user = User.find_by_encoded_id(params[:id])
    dimensions = params[:d]
    style = params[:s]

    url = default_image_url(user, dimensions, style, true)

    if Rails.env.development?
      img = open(Rails.public_path+url)
      send_data(
        img.read,
        :type => 'image/png',
        :disposition => 'inline'
      )
    else
      redirect_to url
      #render :nothing => true, :status => 404
    end
  end

  def following_users
    #@user = User.find_by_encoded_id(params[:id])
    #@title = "#{@user.fullname} following" if @user
    #@following_users = User.where(:_id.in => @user.following_users).order_by([[:first_name, :asc], [:last_name, :desc]])
    #if params[:format] == :api
    #  following = []
    #  @following_users.each do |user|
    #    following << User.convert_for_api(user, current_user)
    #  end
    #  response = {:json => {:status => 'ok', :data => following}}
    #  render response
    #end
  end

  def followers
    #@user = User.find_by_encoded_id(params[:id])
    #@title = "#{@user.fullname} followers" if @user
    #@followers = User.followers(@user.id)
    #if params[:format] == :api
    #  followers = []
    #  @followers.each do |user|
    #    followers << User.convert_for_api(user, current_user)
    #  end
    #  response = {:json => {:status => 'ok', :data => followers}}
    #  render response
    #end
  end

  def settings
    @user = current_user
    unless signed_in?
      redirect_to :root
    end
    @locations = City.order_by([[:state_code, :asc], [:city, :asc]]).all
  end

  # BETA REMOVE?
  #def settings_update
  #  current_user.toggle_setting(params[:setting])
  #  current_user.save
  #  render :json => {:status => 'ok', :event => 'settings_updated', :target => '.setting-'+params[:setting], :toggle_classes => ['setB', 'unsetB']}, :status => 201
  #end

  def tweet
    if params[:tweet_content]
      current_user.twitter.update(params[:tweet_content])
    end

    render :json => build_ajax_response(:ok, root_path, 'Tweet Successful!')
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def user_link(user, length=nil, base='')
    name = if length then truncate(user.fullname, :length => length, :omission => '..') else user.fullname end
    render "users/link", :user => user, :name => name, :base => base
  end

end

app/views/users/_auto_helper.html.erb
<div class="auto-user">
  <% img = default_image_url(@user, [30, 30]) %>
  <%= image_tag img[:url], img[:options].merge!({:class => 'profileImage'}) if img %>
  <div class="name">
    <%= @user.fullname %>
  </div>

  <div class="location">
    <%= @user.location.full %>
  </div>
</div>

app/views/users/_header.html.erb
<% if signed_in? %>

  <div id="page-header">

    <%= image_tag user_default_picture_path(@user, :d => [150, 150], :s => 'square'), :style => "max-width: 150px;", :class => 'main-image', :alt => '' %>

    <div class="details">
      <h1><%= @user.fullname %></h1>

      <% if signed_in? && current_user.role?('admin') %>
        <% if @user.id != current_user.id %>
          <!--<a class="user-switch" href="{{ path('homepage', {'_switch_user': user.username}) }}">Impersonate User</a>-->
        <% end %>
      <% end %>


      <div class="sub-head">
        <%= @user.location.full %>
      </div>

      <%= render "follows/button", target_user: @user %>
      <%= render "pings/button", target_user: @user %>
    </div>

    <ul class="nav">
      <li>
        <a class="<%= controller.action_name == 'show' ? 'on' : '' %>" href="<%= user_path(@user) %>">
          <% if current_user == @user %>
            My Post
          <% else %>
            <%= @user.first_name %>'s Post
          <% end %>
        </a>
      </li>
      <li>
        <a class="<%= controller.action_name == 'following_users' ? 'on' : '' %>" href="<%= user_following_users_path(@user) %>">Following</a>
      </li>
      <li>
        <a class="<%= controller.action_name == 'followers' ? 'on' : '' %>" href="<%= user_followers_path(@user) %>">Followers</a>
      </li>
      <% if signed_in? && current_user.id == @user.id %>
        <li>
          <a class="<%= controller.action_name == 'settings' ? 'on' : '' %>" href="<%= user_settings_path(@user) %>">Settings</a>
        </li>
      <% end %>
    </ul>

    <ul class="right-info">
      <li>Joined <%= time_ago_in_words(@user.created_at, false) %> ago</li>
      <li>Last login <%= time_ago_in_words(@user.last_sign_in_at, false) %> ago</li>
      <li>Following: <%= @user.following_users_count.to_i %></li>
      <li>Followers: <%= @user.followers_count.to_i %></li>
      <li>Lifetime Pings: <%= @user.pings_count.to_i %></li>
      <li>Lifetime Loop-Ins: <%= @user.votes_count.to_i %></li>
    </ul>
  </div>

<% end %>

app/views/users/_image_upload_js.html.erb
<script>
  $(function() {
    var user_image_uploader = new plupload.Uploader({
      runtimes : "flash,browserplus,gears,silverlight,html5",
      browse_button : 'user_uploadB',
      max_file_size : '2mb',
      url : "<%= upload_tmp_path %>",
      container: 'user_uploadB',
      flash_swf_url: "/assets/javascripts/plupload/plupload.flash.swf",
      silverlight_xap_url: "/assets/javascripts/plupload/plupload.silverlight.xap",
      multipart: true,
      multipart_params: {
        "authenticity_token" : '<%= form_authenticity_token %>'
      }
    });

    user_image_uploader.bind('FilesAdded', function(up, files) {
    });

    user_image_uploader.bind('QueueChanged', function() {
      console.log('File Added');
      user_image_uploader.start();
    })

    user_image_uploader.bind('UploadProgress', function(up, file) {
      console.log(file.percent + "%");
    });

    user_image_uploader.bind("FileUploaded", function(up, file, data) {
      params = $.parseJSON(data.response);
      $.ajax({
        url: '<%= user_picture_update_path %>',
        dataType: 'json',
        type: 'put',
        data: {image_location: params.image_path},
        success: function(response) {
          $('#page-header .main-image,#sidebar .profile_image img').each(function(i,val) {
            var img_src = $(val).attr('src');
            var timestamp = new Date().getTime();
            $(val).attr('src',img_src+'&'+timestamp);
          });
        }
      })
    })

    user_image_uploader.init();
  });
</script>

app/views/users/_link.erb
<%= link_to name, base+user_path(user), :class => 'ulink' %>

app/views/users/_teaser.html.erb
<div class="teaser user">
  <%= image_tag user_default_picture_path(user, :d => [50, 50], :s => 'square'), :style => "max-width: 50px;", :class => 'profileImage', :alt => '' %>
  <%= user_link user %>
  <%= render 'follows/button', :target_user => user %>
  <%= render "pings/button", target_user: user %>
  <div class="clear"></div>
</div>

app/views/users/_undecided.html.erb
<div class="undecidedC collapsed">
  <div class="bg"></div>
  <div class="side-toggle" title="Hide/Show the undecided list"></div>
  <div class="wrap">
    <h5>Undecided Users</h5>
    <% users.each do |user| %>
      <% cache("#{user.id.to_s}-undecided") do %>
      <div class="item">
        <a class="profile-image" href="<%= user_path user %>" title="<%= user.fullname %>">
          <%= image_tag user_default_picture_path(user, :d => [30, 30], :s => 'square'), :style => "max-width: 30px;", :alt => '' %>
        </a>
        <%= user_link user, 12 %>
      <% end %>
        <%= render "pings/button", :current_user => @user, :target_user => user %>
      </div>
    <% end %>

    <% if users.length == 0 %>
      <div class="none">None!</div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<% content_for :user_header do %>
  <%= render 'users/header' %>
<% end %>

<% if current_user.id == @user.id || current_user.following_user?(@user.id) %>
  <% if !@followers.empty? %>
    <ul class="user-list">
      <% @followers.each do |follower| %>
        <%= render 'users/teaser', :user => follower %>
      <% end %>
    </ul>
  <% else %>
    <div class="none"><%= @user.first_name %> has no followers</div>
  <% end %>
<% else %>
  <div class="none">You must follow <%= @user.first_name %> to see <%= @user.gender_possesive %> followers</div>
<% end %>

app/views/users/following_users.html.erb
<% content_for :user_header do %>
  <%= render 'users/header' %>
<% end %>

<% if current_user.id == @user.id || current_user.following_user?(@user.id) %>
  <% if !@following_users.empty? %>
    <ul class="user-list">
      <% @following_users.each do |follower| %>
        <%= render 'users/teaser', :user => follower %>
      <% end %>
    </ul>
  <% else %>
    <div class="none"><%= @user.first_name %> is not following anyone</div>
  <% end %>
<% else %>
  <div class="none">You must follow <%= @user.first_name %> to see who <%= @user.gender_pronoun %> follows</div>
<% end %>

app/views/users/settings.html.erb
<% content_for :content do %>
  <div id="user-settings">
  
    <section class="location-settings">
      <h3>My Location</h3>
      <select id='my-location' data-url='<%= user_change_location_path %>' autocomplete='off'>
        <% @locations.each do |location| %>
          <option value='<%= location.id %>' <%= 'selected' if location.id == @user.location.id %>><%= location.fullname %></option>
        <% end %>
      </select>
    </section>
  
    <section class="email-settings">
      <h3>Emails / Push Notifications</h3>
  
      <div class="email-note">Note: if you have The Whoot app for iPhone or Android, you will be notified through the apps instead of email.</div>
  
      <div class="field">
        <div class="setting-text">When someone follows me</div>
        <div class="btn-group">
          <div class="btn radio-btn <%= "btn-info" if @user.settings.email_follow %>" name="email_follow" data-value="true">On</div>
          <div class="btn radio-btn <%= "btn-info" unless @user.settings.email_follow %>" name="email_follow" data-value="false">Off</div>
        </div>
      </div>
  
      <div class="field">
        <div class="setting-text">When someone pings me</div>
        <div class="btn-group">
          <div class="btn radio-btn <%= "btn-info" if @user.settings.email_ping %>" name="email_ping" data-value="true">On</div>
          <div class="btn radio-btn <%= "btn-info" unless @user.settings.email_ping %>" name="email_ping" data-value="false">Off</div>
        </div>
      </div>

      <div class="field">
        <div class="setting-text">When someone loops in to my night</div>
        <div class="btn-group">
          <div class="btn radio-btn <%= "btn-info" if @user.settings.email_loop %>" name="email_loop" data-value="true">On</div>
          <div class="btn radio-btn <%= "btn-info" unless @user.settings.email_loop %>" name="email_loop" data-value="false">Off</div>
        </div>
      </div>
  
      <div class="field">
        <div class="setting-text">When someone comments on something I said</div>
        <div class="btn-group">
          <div class="btn radio-btn <%= "btn-info" if @user.settings.email_comment %>" name="email_comment" data-value="true">On</div>
          <div class="btn radio-btn <%= "btn-info" unless @user.settings.email_comment %>" name="email_comment" data-value="false">Off</div>
        </div>
      </div>
  
      <% if @user.device_token %>
        <h3 class="lower-header">Daily Reminder</h3>
        <div class="field">
          <div class="setting-text">Send me a daily app notification reminding me to post</div>
          <div class="btn-group">
            <div class="btn radio-btn <%= "btn-info" if @user.settings.email_daily %>" name="email_daily" data-value="true">On</div>
            <div class="btn radio-btn <%= "btn-info" unless @user.settings.email_daily %>" name="email_daily" data-value="false">Off</div>
          </div>
        </div>
      <% end %>
    </section>
  </div>
<% end %>