config/routes.rb
Whoot::Application.routes.draw do

  match '(*any)' => redirect { |p, req| req.url.sub('www.', '') }, :constraints => { :host => /^www\./ }

  scope 'api' do
    scope 'v2' do
      scope 'posts' do
        get 'feed' => 'api_posts#feed', :defaults => { :format => :api }
        get ':id' => 'api_posts#show', :defaults => { :format => :api }
        post '' => 'api_posts#create', :defaults => { :format => :api }

        scope 'loop_ins' do
          post '' => 'api_loop_ins#create', :type => 'User', :defaults => { :format => :api }
          delete '' => 'api_loop_ins#destroy', :type => 'User', :defaults => { :format => :api }
        end
      end

      scope 'users' do
        scope 'follows' do
          post '' => 'api_follows#create', :type => 'User', :defaults => { :format => :api }
          delete '' => 'api_follows#destroy', :type => 'User', :defaults => { :format => :api }
        end

        scope 'blocked' do
          post '' => 'api_users#block_user', :defaults => { :format => :api }
          get '' => 'api_users#blocked_users', :defaults => { :format => :api }
          delete '' => 'api_users#unblock_user', :defaults => { :format => :api }
        end

        scope 'pings' do
          post '' => 'api_pings#create', :type => 'User', :defaults => { :format => :api }
        end

        put '' => 'api_users#update', :defaults => { :format => :api }
        put 'location' => 'api_users#change_location', :defaults => { :format => :api }, :as => :user_change_location
        post 'night_invites' => 'api_users#night_invite', :defaults => { :format => :api }
        get 'me' => 'api_users#me', :defaults => { :format => :api }
        get 'undecided' => 'api_users#undecided', :defaults => { :format => :api }
        get 'notifications' => 'api_users#notifications', :defaults => { :format => :api }
        get ':id/activity' => 'api_users#activity', :defaults => { :format => :api }
        get ':id/following_users' => 'api_users#following_users', :defaults => { :format => :api }
        get ':id/followers' => 'api_users#followers', :defaults => { :format => :api }
        get ':id' => 'api_users#show', :defaults => { :format => :api }
      end

      scope 'comments' do
        post '' => 'api_comments#create', :as => :comments_create, :defaults => { :format => :api }
      end

      scope 'invites' do
        post 'phone_numbers' => 'invites#invite_phone_numbers', :defaults => { :format => :api }
        get 'show_invite_screen' => 'invites#show_invite_screen', :defaults => { :format => :api }
      end

      scope 'shouts' do
        post '' => 'shouts#create', :defaults => { :format => :api }
      end

      get 'locations' => 'api_locations#index', :defaults => { :format => :api }
      get 'facebook-friends' => 'api#facebook_friends', :defaults => { :format => :api, :version => :v2 }
      get 'analytics' => 'api_users#analytics', :as => :analytics, :defaults => { :format => :api }
      get 'generate_token' => 'api#generate_token', :as => :mobile_generate_token, :defaults => { :format => :api }
      post 'set_device_token' => 'api#set_device_token', :as => :set_device_token, :defaults => { :format => :api }
    end

    scope 'v1' do
      get 'generate_token' => 'api#generate_token', :as => :mobile_generate_token, :defaults => { :format => :api }
      post 'set_device_token' => 'api#set_device_token', :as => :set_device_token, :defaults => { :format => :api }
      get 'posts' => 'api#posts', :defaults => { :format => :api }
      post 'posts' => 'posts#create', :defaults => { :format => :api }
      get 'posts/:id/comments' => 'api#comments', :defaults => { :format => :api }
      post 'posts/comments' => 'comments#create', :defaults => { :format => :api }
      get 'posts/:id/votes' => 'api#votes', :defaults => { :format => :api }
      post 'posts/votes' => 'votes#create', :defaults => { :format => :api }
      post 'follow' => 'follows#create', :defaults => { :format => :api }
      delete 'follow' => 'follows#destroy', :defaults => { :format => :api }
      post 'ping' => 'pings#create', :defaults => { :format => :api }
      get 'undecided' => 'api#undecided', :defaults => { :format => :api }
      get 'facebook-friends' => 'api#facebook_friends', :defaults => { :format => :api, :version => :v1 }
      get 'users/me' => 'api#me', :defaults => { :format => :api }
      get 'users/:id/following' => 'users#following_users', :defaults => { :format => :api }
      get 'users/:id/followers' => 'users#followers', :defaults => { :format => :api }
      get 'users/:id' => 'users#show', :defaults => { :format => :api }
      post 'invites/phone_numbers' => 'invites#invite_phone_numbers', :defaults => { :format => :api }
      get 'invites/show_invite_screen' => 'invites#show_invite_screen', :defaults => { :format => :api }
    end
  end

  scope 'm' do
    scope 'p' do
      get ':id' => 'mobile#post_show'
    end
  end

  get 'settings' => 'users#settings', :as => :user_settings
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  get '/users/auth/:provider' => 'omniauth_callbacks#passthru'

  scope "/users" do
    put "/picture" => "users#picture_update", :as => :user_picture_update
    get ':id/picture' => 'users#default_picture', :as => :user_default_picture
    put '/location' => 'users#change_location'
  end

  get ':id/following' => 'users#show', :as => :user_following_users
  get ':id/followers' => 'users#show', :as => :user_followers

  resque_constraint = lambda do |request|
    request.env['warden'].authenticate? and request.env['warden'].user.role?('admin')
  end

  constraints resque_constraint do
    mount Resque::Server, :at => "admin/resque"
  end

  mount Soulmate::Server, :at => "soul-data"

  resources :invites, :only => [:create, :index]

  resources :posts, :only => [:new]

  get 'testing' => 'testing#test', :as => :test

  get ':id' => 'users#show', :as => :user

  scope 'pages' do
    get 'about' => 'pages#about', :as => :about
    get 'contact' => 'pages#contact', :as => :contact
    get 'terms' => 'pages#terms', :as => :terms
    get 'privacy' => 'pages#privacy', :as => :privacy
    get 'faq' => 'pages#faq', :as => :faq
    get 'team' => 'pages#team', :as => :team
  end

  root :to => "pages#home"

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!

  def show
    @post = NormalPost.find(params[:id])
    @voters = User.where(:_id.in => @post.voters)
    comments = Comment.where(:post_id => @post.id, :status => 'Active') # aren't these embedded?
    @comments_with_user = User.join(comments)

    details = render_to_string :show

    render json: {:status => 'success', :details => details }
  end

  def new
  end

  def create
    @post = Post.current_post(current_user)

    if params[:post][:tag] && params[:post][:tag][:name]
      params[:tag] = params[:post][:tag][:name]
    end

    if @post
      @post.attributes = params[:post]
      @post.venue = nil if @post.address_original.blank? && params[:post][:venue][:address_string].blank?
    else
      @post = Post.new(params[:post])
      @post.set_user_snippet(current_user)
    end

    if params[:format] && params[:format] == :api
      @post.entry_point = 'api'
    else
      @post.entry_point = 'website'
    end

    redirect = Post.where("user_snippet._id" => current_user.id).first ? request.referer : invites_path

    if @post.save
      Pusher[current_user.id.to_s].trigger('post_changed', {:post_id => @post.id.to_s, :user_id => current_user.id.to_s})
      mixpanel_data = {
              'Tag' => (@post.tag ? @post.tag.name : 'none'),
              'Type' => @post.night_type,
              'City' => (@post.location ? @post.location.full : 'none'),
              'Format' => @post.entry_point
      }
      @mixpanel.track_event("Post Create", current_user.mixpanel_data.merge!(mixpanel_data))

      response = { :status => :ok, :redirect => redirect }
      render json: response, status: :created
    else
      render json: {:status => :error, :errors => @post.errors}, status: :unprocessable_entity
    end
  end











  def update_feed_display
    if session[:feed_filters][:display].include? params[:value]
      session[:feed_filters][:display].delete(params[:value])
    else
      session[:feed_filters][:display] << params[:value]
    end

    render json: {:replace_target => '#page_content', :content => render_cell(:post, :feed), :event => 'updated_feed_filters'}
  end

  def update_feed_sort
    session[:feed_filters][:sort][:target] = params[:value]

    render json: {:replace_target => '#page_content', :content => render_cell(:post, :feed)}
  end

  def map
    posts = Post.following_feed(current_user, session[:feed_filters], false).to_a
    venues = Array.new
    venue_ids = Hash.new
    venue_count = 0
    posts.each do |post|
      if post.venue
        unless venue_ids.key? post.venue.id
          venue_ids[post.venue.id] = venues.length
          venues << {:id => post.venue.id.to_s, :coordinates => post.venue.coordinates, :count => 0, :name => post.venue_pretty_name, :location => post.venue.city}
          venue_count += 1
        end
        venues[venue_ids[post.venue.id]][:count] += 1
      end
    end

    venues.sort_by! {|venue| venue[:count]}
    venues.reverse!
    images = ["map_pin_fill_14x23.png","map_pin_fill_18x29.png","map_pin_fill_24x38.png","map_pin_fill_30x48.png"]
    venues_with_image = venues.each_with_index do |venue, i|
      venue[:image] = case venue[:count]
        when 1..2 then images[0]
        when 3..6 then images[1]
        when 7..15 then images[2]
        else images[3]
      end
    end

    venues = Hash.new

    venues_with_image.map do |venue|
      venues[venue[:location]] ||= Array.new
      venues[venue[:location]] << venue
    end

    @mixpanel.track_event("View Map", current_user.mixpanel_data)

    html = render_to_string :partial => 'map', :locals => {:locations => venues}
    render :json => {:status => 'OK', :content => html, :event => 'post_map_loaded'}
  end

  def ajax
    post = Post.find(params[:post_id])
    html = render_to_string :partial => 'teaser', :locals => {:post => post}
    response = {:status => 'OK', :post => html }
    render json: response, status: 200
  end

end

app/views/posts/_event.html.erb
<div class="teaser event <%= event._type %> <%= 'last' if last %>" id="c-<%= event.id %>">

  <div class="media">
    <%= image_tag user_default_picture_path(event.user, :d => [30, 30], :s => 'square'), :alt => '' %>
    <div class='icon <%= event.icon %>'></div>
  </div>

  <div class="content">
    <p>
      <%= user_link(event.user, 15) %>
      <%= event.text.html_safe %>

      <% if event.comment? %>
        <% #TODO: Change this workaround to cancan (getting "can?" method undefined): if can? :destroy, comment %>
        <% if current_user.id == event.comment.user_snippet.id || current_user.id == event.comment.has_comments._parent.user_snippet.id || current_user.role?("admin") %>
          <div class="ac disable conf hide" title="delete this comment" data-m="DELETE" data-url="<%= comment_path event.comment %>">X</div>
        <% end %>
      <% end %>  
    </p>
    
    <div class="time"><%= time_ago_in_words event.created_at, false %> ago</div>
  </div>
</div>

app/views/posts/_event_feed.html.erb
<% post.post_events.reverse.each_with_index do |event,i| %>
  <%= render "posts/event", :event => event, :current_user => current_user, :last => (post.post_events.length == i+1 ? true : nil) %>
<% end %>

app/views/posts/_feed.html.erb
<% posts.each do |post| %>
  <%= render "posts/teaser", :post => post, :current_user => user %>
<% end %>

<% if posts.length == 0 %>
  <div class="no-posts">No posts to show!</div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for Post.new, :html => { :class => 'ajax' } do |f| %>

  <div class="errors"></div>

  <h4>Hey <%= user.first_name %>, what are you doing tonight?</h4>

  <div class="type working <%= 'on' if post.night_type == 'working' %>" data-val="working">Working</div>
  <div class="type low_in <%= 'on' if post.night_type == 'low_in' %>" data-val="low_in">Staying In</div>
  <div class="type low_out <%= 'on' if post.night_type == 'low_out' %>" data-val="low_out">Relaxing Out</div>
  <div class="type big_out <%= 'on' if post.night_type == 'big_out' %>" data-val="big_out">Partying</div>
  <div class="clear"></div>

  <%= f.hidden_field :night_type, :class => 'post_type', :autocomplete => 'off', :value => post.night_type %>

  <div class="field lClear">
    <%= f.fields_for :tag do |t| %>
      <%= t.label :name, "Tag your night (optional). 40 character max." %>
      <%= t.text_field :name, :autocomplete => 'off', :value => post.tag ? post.tag.name : '' %>
    <% end %>
  </div>

  <%= render "posts/venue_input", :f => f, :post => post, :venue_label => 'Add Venue (optional). Please choose from suggested results.', :venue_required => '' %>

  <div class="actions">
    <%= f.submit "Submit Post", :class => 'submit', :autocomplete => 'off' %>
  </div>
<% end %>

app/views/posts/_map.html.erb
<div class="map">
  <div id="post-map-coordinates" data-lat="<%= current_user.location.coordinates[1] %>" data-lon="<%= current_user.location.coordinates[0] %>"></div>
  <div id="post-map-canvas"></div>
</div>
<div class="venues">
  <h5>Where Your Friends Are Going</h5>
  <% locations.each do |location,venues| %>
    <h6><%= location %></h6>
    <% venues.each_with_index do |venue,i| %>
      <% if venue[:coordinates] %>
        <div class="venue"
             data-id="<%= venue[:id] %>"
             data-lat="<%= venue[:coordinates][1] %>"
             data-lon="<%= venue[:coordinates][0] %>"
             data-icon="<%= venue[:image] %>"
             data-name="<%= venue[:name] + ' - ' + venue[:count].to_s + ' friends' %>"
             data-url="<%= attending_venue_map_path venue[:id] %>"
             data-sort="<%= i %>">
          <div class="name">
            <%= venue[:name] %>
          </div>
          <div class="num">
            <%= pluralize(venue[:count], 'friend') %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/posts/_teaser.html.erb
<%# cache(post.teaser_cache_key(current_user)) do %>
<div class="teaser post <%= post.night_type %>" id="<%= "post-#{post.user_snippet.id}" %>" data-venue-id="<%= post.venue.id.to_s if post.venue %>">

  <div class="head">
    <a class="profile-image" href="<%= user_path post.user_snippet %>" title="<%= post.user_snippet.fullname %>">
      <%= image_tag user_default_picture_path(post.user_snippet, :d => [50, 50], :s => 'square'), :style => "max-width: 50px;", :alt => '' %>
    </a>

    <div class="ulink-wrap">
      <%= user_link(post.user_snippet, 15) %>
    </div>

    <div class="what">
      <%= post.night_type_short %>
    </div>

    <div class="tags">
      <% if post.tag %>
        <%= render "tags/teaser", :tag => post.tag %>
      <% end %>

      <% if post.venue %>
        <div class='icon map-pin-small' title='<%= post.user_snippet.first_name %> posted a venue for the night'></div>
      <% end %>
      <% if post.entry_point == 'api' %>
        <div class='icon phone-small' title='<%= post.user_snippet.first_name %> posted from The Whoot mobile app'></div>
      <% end %>
    </div>

    <div class="comments_count">
      <div class="icon comment-grey-1614"></div>
      <span><%= post.comment_count.to_i %></span>
    </div>
    <%= render "votes/button", :target => post, :current_user => current_user %>
    <div class='arrow-fat-down'></div>
    <div class='arrow-fat-up'></div>
  </div>

  <div class="details two-col-equal-height hide">
    <div class="left voters">
      <h4><%= post.user_snippet.first_name %>'s loop</h4>
      <%= render "votes/voters", :post => post %>
    </div>

<%# end %>

    <div class="right">
      <% if post.has_venue? %>
        <h4 class="venue">@ <%= post.venue_pretty_name %></h4>
        <% if post.venue && post.venue.address %>
          <div class='address'><%= post.venue.full_address %></div>
        <%end %>
      <% end %>
      <div class="comment-feed cf-<%= post.id %>">
        <%= render "comments/form", :post => post, :current_user => current_user %>
        <%= render "posts/event_feed", :post => post, :current_user => current_user %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_venue_input.html.erb
<div class="venue_input">
  <%= f.fields_for :venue do |v| %>
    <div class="field lClear <%= venue_required %>">
      <%= v.hidden_field :name, :autocomplete => 'off', :class => 'name', 'data-url' => venue_autocomplete_path(:city => @user.location.id) %>
    </div>
    <div class="field lClear address_fields <%= venue_required %>">
      <%= v.label :address, venue_label, :for => "#{f.object.class.name.underscore}_address_placeholder" %>
      <input type="text" name="<%= "#{f.object.class.name.underscore}[address_original]" %>" value="<%= post.address_original %>" id="<%= "#{f.object.class.name.underscore}_address_placeholder" %>" class="address_placeholder" placeholder="" autocomplete="off" />
      <%= v.hidden_field :address_string, :autocomplete => 'off', :class => 'address' %>
    </div>
    <%= v.hidden_field :coordinates_string, :autocomplete => 'off', :class => 'coordinates' %>
    <%= v.hidden_field :phone, :autocomplete => 'off', :class => 'phone' %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/new.html.erb
<div class='top'>
  <%= image_tag "logo-top.png", :alt => "The Whoot", :class => 'logo' %>
  <!--<a href="/users/sign_out" class='logout'>Logout</a>-->
</div>

app/views/posts/show.html.erb
<div class="post-details normal two-col-equal-height">
  <div class="left voters">
    <h4>+1's</h4>
    <%= render "votes/voters", :voters => @voters %>
  </div>

  <div class="right">
    <% if @post.has_venue? %>
      <h4 class="venue">@ <%= @post.venue_pretty_name %></h4>
    <% end %>
    <div class="comment-feed cf-<%= @post.id %>">
      <%= render "comments/form", :post => @post %>
      <%= render "comments/feed", :comments => @comments_with_user %>
    </div>
  </div>
  <div class="clear"></div>
</div>